### PR TITLE
Use replace-buffer-contents to update formatting

### LINKED ISSUE #15: Apply patch instead of replacing whole buffer
Replacing the entire buffer with `copy-to-buffer` is disruptive: It's a delete followed by a replace, and many links within emacs (including compilation, grep, and occur buffers) will overreact to the deletion by redirecting all links to the beginning of the file. (Reinserting the whole file also causes it to be reparsed for syntax highlighting, which can be kind of slow)

The support for `gofmt` in `go-mode` shows a better way, although it's unfortunately a nontrivial amount of code. `go-mode` asks for a diff instead of rewriting the whole file, then [parses the diff](https://github.com/dominikh/go-mode.el/blob/120fb911f1d8038f828da85eed8aaad977dabd8c/go-mode.el#L1019-L1061) and translates it into editing commands. It would be nice if `blacken` did the same (It would be even nicer if there were one meta-`fmt` mode for emacs so that this wheel doesn't have to be reinvented for every formatting tool).

### LINKED ISSUE #33: Blacken mode does not save excursion
# My Environment

- OS: MX Linux 18
- Result of `$ uname -r`: 4.19.0-5-amd64
- [dotfiles](https://github.com/mrbig033/dotfiles)
- i3 version 4.13
- [~/.config/i3](https://github.com/mrbig033/dotfiles/blob/master/i3/config)
- GNU Emacs 27.0.50
- [~/.emacs.d](https://github.com/mrbig033/emacs)
- blacken-20190917.535

# Issue

Rich now blacken-mode does not save-excursion in most of the cases. This breaks the flow of the coding, because every time I run `blacken-buffer`, or it is run automatically, the cursor goes either to the beginning of the buffer, or to some random place. This makes it impossible to use auto-save modes such as `super-save`, which are extremely useful. This bug is preventing me from using `blacken-mode`, which is otherwise extremely useful.

### PR DESCRIPTION
**Pull request by ljos**
blacken.el (blacken-buffer): Use replace-buffer-contents to update
formatting after running black. This is potentially slower than using
copy-to-buffer, but it keeps the position of point etc (if it can). 

blacken.el (blacken-replace-buffer-contents-max-secs): Add new
variable to control how long to spend calculating
replac-buffer-contents.

Fixes #33
Fixes #15

### CODE REVIEW

**Comment by ljos** [comment]
I set the `blacken-replace-buffer-contents-max-secs` to nil as setting it can lead to unexpected behaviour if the timeout is reached sometimes, but not others. Then the buffer is replaced in its entirety and we lose position again.

The other issue is that `replace-buffer-contents` was introduced in emacs 26.1, so this change drops support for versions previous to that.

**Comment by dakra** [comment]
Personally I don't use `blacken` but `replace-buffer-contents` only got added Emacs 26 and the MAX-SEC parameter only Emacs 27.

I guess we could drop Emacs 25 support? But depending on Emacs 27 is surely too new.

Also I read about a couple of problems already with `replace-buffer-contents`.
https://github.com/purcell/emacs-reformatter/blob/b57f5d480003ab7b0880e0059dcc51747fb2e088/reformatter.el#L296

**Comment by ljos** [comment]
I wasn't aware of reformatter. I would suggest it is probably more robust using that. I see that there is already an alternative using it on GitHub: https://github.com/wbolster/emacs-python-black

**Comment by dakra** [comment]
Yes. I guess emacs-python-black is better maintained than this repository here (which is on life support only ;)

Personally I use https://github.com/raxod502/apheleia and are happy with it.

**Pull request closed without merging**
